version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: nutrition-app-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nutrition-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - nutrition-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nutrition-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/nutrition-app?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - nutrition-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nutrition-app-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - nutrition-network

volumes:
  mongodb_data:

networks:
  nutrition-network:
    driver: bridge 